import Head from 'next/head';
import React, { FC } from 'react'

const ExpirePage = ({  }) => {
  return (
    <div>
    <Head>
      <title>Verify App</title>
      <meta
        content="Generated by @rainbow-me/create-rainbowkit"
        name="description"
      />
      <link href="/favicon.ico" rel="icon" />
    </Head>

    <main className="h-screen flex flex-col justify-center items-center text-white">
      <h1 className="text-4xl pb-8">Expired</h1>
      <p className="">
        This page is already expired.
      </p>
    </main>
  </div>
  )
}

export default ExpirePage;