import { ConnectButton } from "@rainbow-me/rainbowkit";
import type { NextPage } from "next";
import Head from "next/head";
import { GetAssetsRes, NFT } from "@/components/nft/NFT";
import { Key, useEffect, useState } from "react";
import { useAccount, useDisconnect, useSignMessage } from "wagmi";
import Wallet from "@/components/wallet/index";
import useOwnerTokenId from "@/services/hook/useOwnerToTokenId";
import useWallet from "@/services/hook/useWallet";
import { ariseSoulAddress } from "@/constants";

const Home: NextPage = () => {
  const [network, setNetwork] = useState<string>("");
  const wallet = useWallet();
  const ownerTokenId = useOwnerTokenId(ariseSoulAddress, wallet);

  // handle account
  const account = useAccount({
    onConnect({ address, connector, isReconnected }) {
      setNetwork(connector!.chains[0].name);
    },
    onDisconnect() { },
  });

  return (
    <div>
      <Head>
        <title>Verify App</title>
        <meta
          content="Generated by @rainbow-me/create-rainbowkit"
          name="description"
        />
        <link href="/favicon.ico" rel="icon" />
      </Head>

      <main className="h-screen flex flex-col justify-center items-center">
      </main>
    </div>
  );
};

export default Home;
